wandb_project: spd-tms
wandb_run_name: null
wandb_run_name_prefix: "topk_"
seed: 0
topk: 2
batch_topk: false
max_sparsity_coeff: 1
topk_l2_coeff: 0.01
batch_size: 2048
steps: 40_000
print_freq: 4000
lr: 1e-3
lr_scale: constant
lr_warmup_pct: 0.1
loss_type: param_match
task_config:
  task_name: tms
  k: 5
  n_features: 5
  n_hidden: 2
  n_instances: 12
  bias_val: 0.0
  train_bias: true
  feature_probability: 0.05
  # Will use param_match_loss instead of recon_loss. File obtained by running spd/scripts/tms/train_tms.py
  pretrained_model_path: spd/scripts/tms/out/tms_n-features5_n-hidden2_n-instances12.pth